MatiasNasif/Fast-delivery

- client/src/pages/views/get-packages.tsx
- client/src/styles/GetPackages.module.css
refactor: modularize get-packages view
> refactor: modularize get-packages view

- client/src/commons/InputPassword.tsx
- client/src/pages/index.tsx
- client/src/pages/views/register.tsx
- client/src/styles/Login.module.css
- client/src/styles/Register.module.css
css modularization, refactoring and componentization
> css modularization, refactoring and componentization

- client/src/commons/card.tsx
- client/src/commons/header.tsx
- client/src/pages/views/start-workday.tsx
- client/src/styles/Card.module.css
- client/src/styles/Header.module.css
- client/src/styles/StartWorkday.module.css
feat: add card, header & css modularization
> feat: add card, header & css modularization

- client/package-lock.json
- client/src/commons/card.tsx
- client/src/pages/views/manage-packages.tsx
- client/src/styles/Manage-packages.module.css
feat: add manage-packages component with fake data
> feat: add manage-packages component with fake data

- client/src/pages/views/add-package.tsx
- client/src/styles/AddPackage.module.css
> feat: add add-package view

- client/src/pages/views/delivery-man-details.tsx
- client/src/styles/DeliveryManDetails.module.css
- client/src/styles/SwitchOnOff.module.css
- client/src/utils/switchOnOff.tsx
refactor: change delivery-mans-details view
> refactor: change delivery-mans-details view

- client/src/pages/views/start-workday.tsx
feat: add data from faker to start-workday
> feat: add data from faker to start-workday

- client/package-lock.json
- client/src/commons/progress.tsx
- client/src/pages/views/manage-delivery-man.tsx
- client/src/pages/views/manage-schedule.tsx
- client/src/styles/ManageDeliveryMan.module.css
- client/src/styles/Progress.module.css
- client/src/styles/Schedule.module.css
- client/src/styles/SwitchDeliveryStatus.module.css
- client/src/utils/SwitchDeliveryStatus.tsx
- client/src/utils/fakerDeliverys.tsx
feat: add data faker into delivery man views
> feat: add data faker into delivery man views

- api/.env
- api/package-lock.json
- api/package.json
- api/src/app.module.ts
- api/src/users/controllers/users.controller.spec.ts
- api/src/users/controllers/users.controller.ts
- api/src/users/dto/create-user.dto.ts
- api/src/users/dto/index.ts
- api/src/users/dto/update-user.dto.ts
- api/src/users/entities/user.entity.ts
- api/src/users/services/users.service.spec.ts
- api/src/users/services/users.service.ts
- api/src/users/users.module.ts
- client/src/pages/views/manage-delivery-man.tsx
- client/src/pages/views/manage-schedule.tsx
- client/src/pages/views/start-workday.tsx
- client/src/styles/ManageDeliveryMan.module.css
feat: db creation and connection mongodb atlas
> feat: db creation and connection mongodb atlas

- client/package-lock.json
- client/package.json
- client/src/commons/InputEmail.tsx
- client/src/commons/InputFullname.tsx
- client/src/commons/InputPasswordCompare.tsx
- client/src/pages/_document.tsx
- client/src/pages/index.tsx
- client/src/pages/views/register.tsx
- client/src/styles/Login.module.css
- client/src/styles/Register.module.css
feat: componentization of inputs on login and register
> feat: componentization of inputs on login and register

- .github/workflows/pipeline.yml
> feat: add pipeline

- api/src/packages/entities/packages.entity..ts
- api/src/users/entities/user.entity.ts
feat: add relationships to Models
> feat: add relationships to Models

- api/src/users/__tests__/users.controller.spec.ts
refactor: add testing for delete user
> refactor: add testing for delete user

- .github/workflows/pipeline.yml
> bugfix: pipeline deploy

- .github/workflows/pipeline.yml
> bugfix: pipeline deployment

- api/src/packages/controllers/packages.controller.ts
- api/src/packages/services/packages.service.ts
feat:add service packagesByUser
> feat:add service packagesByUser

- client/src/pages/index.tsx
bugfix: delete function never used
> bugfix: delete function never used

- api/src/packages/services/packages.service.ts
- client/src/pages/views/delivery-man-details/[id].tsx
- client/src/pages/views/manage-delivery-man.tsx
refactor: connection client/api detailsDelivery
> refactor: connection client/api detailsDelivery

- client/src/commons/packageDetailsCard.tsx
- client/src/pages/views/delivery-man-details/[id].tsx
refactor: delete package to packageDetailsCard
> refactor: delete package to packageDetailsCard

- client/src/pages/views/manage-packages.tsx
- client/src/pages/views/start-workday.tsx
> refactor: connection with api

- api/src/packages/controllers/packages.controller.ts
- api/src/packages/services/packages.service.ts
refactor: add route packagesByDate
> refactor: add route packagesByDate

- api/src/packages/controllers/packages.controller.ts
- api/src/packages/services/packages.service.ts
- api/src/users/services/users.service.ts
- client/src/pages/views/add-package.tsx
- client/src/pages/views/get-packages.tsx
- client/src/pages/views/start-workday.tsx
refactor: conection api to get-packages
> refactor: conection api to get-packages

- client/package-lock.json
- client/package.json
- client/src/commons/header.tsx
- client/src/pages/views/profile/[id].tsx
- client/src/styles/Profile.module.css
> feat: add user profile view

- client/src/commons/withAdminAuth.tsx
- client/src/pages/views/delivery-man-details/[id].tsx
- client/src/pages/views/manage-schedule.tsx
add: validation of admin on your routes
> add: validation of admin on your routes

- client/src/commons/daySlide.tsx
- client/src/pages/views/manage-schedule.tsx
bugfix: correction slides date
> bugfix: correction slides date

- client/src/commons/daySlide.tsx
- client/src/pages/views/manage-packages.tsx
- client/src/pages/views/manage-schedule.tsx
- client/src/store/dateSelected.ts
- client/src/store/store.ts
refactor: add filter to packages for day
> refactor: add filter to packages for day

- client/src/components/google-maps.tsx
- client/src/pages/views/current-distribution.tsx
bugfix: refresh page with working map
> bugfix: refresh page with working map

- client/src/pages/views/add-package.tsx
- client/src/pages/views/manage-delivery-man.tsx
- client/src/pages/views/manage-packages.tsx
refactor: routes admin protected
> refactor: routes admin protected

- client/src/commons/packageDetailsCard.tsx
- client/src/components/google-maps.tsx
- client/src/pages/views/current-distribution.tsx
- client/src/store/packageIdSelected.tsx
- client/src/store/store.ts
refactor: add start shift button to distribution
> refactor: add start shift button to distribution

- client/src/components/google-maps.tsx
- client/src/pages/views/current-distribution.tsx
bugfix: changes current distribution
> bugfix: changes current distribution

- client/src/pages/index.tsx
- client/src/pages/views/get-packages.tsx
- client/src/styles/GetPackages.module.css
refactor: disable button and remove password recovery
> refactor: disable button and remove password recovery

- api/src/packages/dtos/packages.dto.ts
- api/src/packages/services/packages.service.ts
- client/package-lock.json
- client/src/commons/InputAdress.tsx
- client/src/commons/InputDatePicker.tsx
- client/src/commons/InputReceiver.tsx
- client/src/commons/InputWeight.tsx
- client/src/pages/views/add-package.tsx
- client/src/styles/globals.css
bugfix: addpackages validations
> bugfix: addpackages validations

- client/src/pages/views/current-distribution/[id].tsx
- client/src/pages/views/get-packages.tsx
- client/src/pages/views/manage-delivery-man.tsx
- client/src/styles/GetPackages.module.css
> bugfix: change to develop

- .github/workflows/pipeline.yml
> bugfix: change pipeline

- .github/workflows/pipeline.yml
bugfix: comment checkout repo deploy ec2
> bugfix: comment checkout repo deploy ec2

- .github/workflows/pipeline.yml
bugfix: pipeline included checkout repo deploy ec2
> bugfix: pipeline included checkout repo deploy ec2

- .github/workflows/pipeline.yml
> bugfix: pipeline restore

- .github/workflows/pipeline.yml
bugfix: pipeline with docker-compose up
> bugfix: pipeline with docker-compose up

- .github/workflows/pipeline.yml
bugfix: docker compose build changes
> bugfix: docker compose build changes

- .github/workflows/pipeline.yml
> restore pipeline

- .github/workflows/pipeline.yml
bugfix: docker compose with pipeline
> bugfix: docker compose with pipeline

- .github/workflows/pipeline.yml
- api/Dockerfile
bugfix: pipeline docker compose
> bugfix: pipeline docker compose

- .github/workflows/pipeline.yml
bugfix: pipeline docker compose sudo
> bugfix: pipeline docker compose sudo

- .github/workflows/pipeline.yml
> bugfix: pipeline only bitovi

- api/Dockerfile
bugfix: changes dockerfile api
> bugfix: changes dockerfile api

- docker-compose.yml
bugfix: changes docker compose environment
> bugfix: changes docker compose environment

- api/Dockerfile
bugfix: changes dockerfile api node modules
> bugfix: changes dockerfile api node modules

- api/Dockerfile
- docker-compose.yml
bugfix: delete api docker compose
> bugfix: delete api docker compose

- api/Dockerfile
- docker-compose.yml
bugfix: restore docker api and comment docker compose api y client
> bugfix: restore docker api and comment docker compose api y client

- client/package.json
- client/src/commons/header.tsx
- client/src/pages/index.tsx
- client/src/pages/views/add-package.tsx
- client/src/pages/views/get-packages.tsx
- client/src/pages/views/manage-packages.tsx
- client/src/pages/views/start-workday.tsx
- client/src/pages/views/sworn-statement.tsx
- client/src/store/user.ts
- docker-compose.yml
- package.json
> bugfix: change .env client

- client/src/pages/views/add-package.tsx
> bugfix: modify calendar

- api/package.json
- client/cypress.config.ts
- client/cypress/e2e/3-fast-delivery/login.cy.ts
- client/cypress/e2e/3-fast-delivery/manage-schedule.cy.ts
- client/cypress/fixtures/example.json
- client/cypress/support/commands.ts
- client/cypress/support/e2e.ts
- client/package-lock.json
- client/package.json
> add: cypress connection

- client/src/pages/views/delivery-man-details/[id].tsx
- client/src/pages/views/manage-packages.tsx
- client/src/pages/views/start-workday.tsx
bugfix: delete packages and update
> bugfix: delete packages and update

- client/cypress/e2e/integration/login.cy.ts
- client/cypress/e2e/integration/register.cy.ts
feat: test of register and login
> feat: test of register and login

- client/cypress/e2e/integration/add-packages.cy.ts
- client/cypress/e2e/integration/get-packages.cy.ts
feat: test to add and get packages
> feat: test to add and get packages

- api/package-lock.json
- api/package.json
- api/src/auth/controllers/auth.controller.ts
- api/src/forms-sworn/controllers/forms-sworn.controller.ts
- api/src/main.ts
- api/src/packages/controllers/packages.controller.ts
- api/src/users/controllers/users.controller.ts
feat: add swagger documentation to api endpoints
> feat: add swagger documentation to api endpoints

- client/src/pages/views/add-package.tsx
- client/src/pages/views/current-distribution/[id].tsx
- client/src/pages/views/delivery-man-details/[id].tsx
- client/src/pages/views/get-packages.tsx
- client/src/pages/views/manage-delivery-man.tsx
- client/src/pages/views/manage-packages.tsx
- client/src/pages/views/manage-schedule.tsx
- client/src/pages/views/profile/[id].tsx
- client/src/pages/views/start-workday.tsx
- client/src/pages/views/sworn-statement.tsx
- client/src/styles/Profile.module.css
> bugfix: validate routes
